### ISSUE TITLE
Analysing app.json for setting buildpacks and default stack

### ISSUE THREAD

**Issue by abarke** [heroku/builder#26]
Is there any plan to analyse the app.json for parsing out the buildpacks and stack?

e.g. in our `app.json` we have:

```
{
    "buildpacks": [
        {
            "url": "http://artifactory.our-company.com/repo/artifactory-buildpack.tgz"
        },
        {
            "url": "heroku/php"
        }
    ],
    "stack": "ubuntu-16",
}
```

Could you add this functionality or provide a way to configure this in the config.toml in our projects?

**Comment by jkutner** [comment]
@abarke we've had an eye toward the `project.toml` file proposed in https://github.com/buildpack/rfcs/pull/25 (instead of `app.json`). But I'm curious about `config.toml`. Is this a file of your own or is it honored by other frameworks/tools?

**Comment by abarke** [comment]
I know very little about the `config.toml` file. All I know is right now is that I have a project built for deployment using Heroku and it has a `app.json` where the buildpacks and stack are configured. I would assume that if I use a Heroku Buildpacks builder, that it would read the `app.json` file instead of duplicating the config into yet another config file e.g. `config|project.toml`

**Comment by jkutner** [comment]
@abarke thanks for explaining your thinking on this. It's definitely something I want too take into account.

**Comment by edmorley** [comment]
Specifying the builder image (which in turn dictates the stack), and the list of buildpacks is now part of the upstream `project.toml` file definition:
https://github.com/buildpacks/spec/blob/main/extensions/project-descriptor.md#iobuildpacks-optional

...and is already supported by the Pack CLI tool.

Longer term Heroku will be consolidating the various existing metadata files `heroku.yml` and `app.json` into `project.toml`, however, that work needs to happen in other components, that aren't covered by this repository (which is only for the builder images).
