### ISSUE TITLE
Python runtime no longer working for `heroku/buildpacks`

### ISSUE THREAD

**Issue by ruaridhw** [heroku/builder#317]
In the past day or so, I've seen the `heroku` image fail to deploy a Python runtime when it did previously.

```
Building Cloud Native Buildpack-based application with builder heroku/buildpacks:20...
20: Pulling from heroku/buildpacks
Digest: sha256:c3de68f2f4a14abd2c1cd59c59669dcf1c3f45bb2dd55f635f1ab3a6667e0c
Status: Image is up to date for heroku/buildpacks:20
20-cnb: Pulling from heroku/heroku
Digest: sha256:122102b1fc6585e8c1f5937992b1d0d991b988a7528192f33ad761cb80e3d2
Status: Image is up to date for heroku/heroku:20-cnb
===> ANALYZING
Previous image with name "tmp-cnb-image" not found
===> DETECTING
heroku/python   0.0.0
heroku/procfile 2.0.0
===> RESTORING
===> BUILDING
-----> No Python version was specified. Using the buildpack default: python-3.10.9
       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
 !     Requested runtime 'python-3.10.9' is not available for this stack (heroku-20).
 !     For supported versions, see: https://devcenter.heroku.com/articles/python-support
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

The same job ran fine 29hrs ago with

```
Digest: sha256:1dff41dc11a02d4c8a5c0a5d0e6dacf3ba8c9a4d953cf80f5212710e2d96d14a
Status: Downloaded newer image for heroku/buildpacks:20
Digest: sha256:122102b1fc6585e8c1f5937992b1d041d991b988a7528192f33ad761cb80e3d2
Status: Downloaded newer image for heroku/heroku:20-cnb
```

Did something change with the `heroku/buildpacks:20` that causes the Python runtime to no longer be recognised?

**Comment by ruaridhw** [comment]
Perhaps this is a duplicate of https://github.com/heroku/builder/issues/241 and it's a transient issue...?

**Comment by edmorley** [comment]
Hi!

I've transferred this issue to the `heroku/builder` repository, since the `heroku/stack-images` repository is only for the base images, not the CNB builder. 

(Longer term the best place for language-specific CNB issues will be the CNB repository for the language in question, however for now the builder you are using is using shimmed classic buildpack, so `heroku/builder` is probably the best place for any issues.)

I can't reproduce your issue - it builds fine for me:

```
$ pack --version
0.28.0+git-b10e41f.build-3729
$ mkdir testcase && cd $_
$ echo 'python-3.10.9' > runtime.txt
$ touch requirements.txt
$ pack build --builder heroku/buildpacks:20 --pull-policy always test-image
20: Pulling from heroku/buildpacks
Digest: sha256:c3de68f2f4a14abd2c1c38d59c59669dcf1c3f45bb2dd55f635f1ab3a6667e0c
Status: Image is up to date for heroku/buildpacks:20
20-cnb: Pulling from heroku/heroku
Digest: sha256:122102b1fc6585e8c1f5937992b1d041d991b988a7528192f33ad761cb80e3d2
Status: Image is up to date for heroku/heroku:20-cnb
===> ANALYZING
Previous image with name "test-image" not found
===> DETECTING
1 of 2 buildpacks participating
heroku/python 0.0.0
===> RESTORING
===> BUILDING
-----> Using Python version specified in runtime.txt
-----> Installing python-3.10.9
-----> Installing pip 22.3.1, setuptools 63.4.3 and wheel 0.37.1
-----> Installing SQLite3
-----> Installing requirements with pip
===> EXPORTING
Adding layer 'heroku/python:profile'
Adding layer 'launch.sbom'
Adding 1/1 app layer(s)
Adding layer 'launcher'
Adding layer 'config'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
no default process type
Saving test-image...
*** Images (f315455f4726):
      test-image
Adding cache layer 'heroku/python:shim'
Successfully built image test-image
```

It's worth noting that this error message is shown both when the Python version doesn't exist, and also when the request to check whether it exists fails. However, the request is already retried multiple times, so this should be unlikely:
https://github.com/heroku/heroku-buildpack-python/blob/01d50e12230b89d450c6a65491bf119e66674c9f/bin/steps/python#L14

> Perhaps this is a duplicate of https://github.com/heroku/builder/issues/241 and it's a transient issue...?

I would say so, yes.

**Comment by ruaridhw** [comment]
@edmorley thanks a lot for the quick reply.

The additional context was very helpful! It turns out to in fact be due to the request to check failing as a result of an internal networking issue within out CI/CD runners. Much appreciated

**Comment by edmorley** [comment]
No problem - glad it helped!

Longer term I have plans (in the new Python CNB) to improve the error message here to distinguish between the version-unavailable and network-issue case, which would make debugging this easier.
